import { SavedCompany } from './storage'

export const SEED_COMPANIES: SavedCompany[] = [
  {
    id: 'demo-equinor',
    savedAt: '2026-05-01T00:00:00.000Z',
    name: 'Equinor',
    description: 'Global energy company headquartered in Stavanger, investing heavily in digital transformation across oil, gas, wind, and solar operations.',
    techStack: {
      frontend: ['React', 'TypeScript', 'Angular'],
      backend: ['Python', 'Java', 'Kotlin', 'C++', 'Rust'],
      cloud: ['Azure', 'AWS', 'Google Cloud Platform'],
      data: ['Databricks', 'Apache Spark', 'Snowflake', 'Power BI', 'dbt'],
      devops: ['Kubernetes', 'Terraform', 'GitHub Actions', 'Docker', 'Helm'],
      mobile: [],
      other: ['SAP', 'OSIsoft PI', 'AVEVA', 'Cognite Data Fusion'],
    },
    teamSize: '2 000+',
    itDepartments: ['Software Engineering', 'Data & Analytics', 'Cloud Platform', 'Digital Operations', 'Cybersecurity', 'OT/IT Integration'],
    hiringSignals: [
      'Expanding cloud engineering capacity across Azure and AWS',
      'Growing data science and ML engineering team for production optimization',
      'Hiring full-stack developers for internal operational platforms',
      'Building out digital twin capabilities for offshore assets',
      'Seeking Cognite Data Fusion specialists',
    ],
    summary: "Equinor runs one of Norway's largest IT operations with a strong cloud-first and data-driven culture. High demand for Azure, Databricks, Python, and Kubernetes skills. Continuous digital transformation of oil & gas operations drives strong consultant demand year-round.",
  },
  {
    id: 'demo-dnb',
    savedAt: '2026-05-02T00:00:00.000Z',
    name: 'DNB',
    description: "Norway's largest financial services group, serving 2.3 million retail and corporate customers through a digital-first banking platform.",
    techStack: {
      frontend: ['React', 'TypeScript', 'Next.js', 'GraphQL'],
      backend: ['Java', 'Kotlin', 'Spring Boot', '.NET', 'Node.js'],
      cloud: ['AWS', 'Azure'],
      data: ['Snowflake', 'Power BI', 'Apache Kafka', 'dbt', 'Apache Spark'],
      devops: ['Kubernetes', 'Jenkins', 'GitHub Actions', 'Terraform', 'Docker'],
      mobile: ['React Native', 'Swift', 'Kotlin'],
      other: ['Pega', 'Salesforce', 'MuleSoft'],
    },
    teamSize: '1 500+',
    itDepartments: ['Software Engineering', 'Mobile', 'Data & AI', 'Cloud Infrastructure', 'Security', 'Open Banking'],
    hiringSignals: [
      'Aggressively hiring cloud and platform engineers',
      'Building AI-driven credit scoring and fraud detection models',
      'Expanding React and React Native teams for consumer banking apps',
      'Open Banking and API platform team growing rapidly',
      'Security and compliance engineering in high demand',
    ],
    summary: 'DNB is in the middle of a full digital transformation, moving from legacy banking infrastructure to a modern cloud-native stack. Strong need for Java/Kotlin backend, React frontend, and Kafka/Snowflake data skills. One of the most active tech employers in Norway.',
  },
  {
    id: 'demo-aize',
    savedAt: '2026-05-03T00:00:00.000Z',
    name: 'Aize',
    description: 'Norwegian software company building industrial intelligence platforms for asset-intensive industries including offshore energy and maritime.',
    techStack: {
      frontend: ['React', 'TypeScript', 'Three.js', 'WebGL'],
      backend: ['Node.js', 'Python', 'Go', 'GraphQL'],
      cloud: ['Azure', 'Azure Kubernetes Service'],
      data: ['PostgreSQL', 'TimescaleDB', 'Azure Data Explorer'],
      devops: ['Kubernetes', 'Helm', 'GitHub Actions', 'Docker', 'Terraform'],
      mobile: [],
      other: ['Digital Twin', 'AVEVA', 'ISO 15926'],
    },
    teamSize: '200–400',
    itDepartments: ['Product Engineering', 'Platform', 'Data & Integrations', 'UX & Design'],
    hiringSignals: [
      'Hiring senior TypeScript and React engineers',
      'Growing backend team with Go and Node.js focus',
      'Seeking 3D/WebGL engineers for digital twin visualization',
      'Platform team expanding Kubernetes and Azure expertise',
    ],
    summary: 'Aize is a product-focused engineering company with a modern cloud-native stack on Azure. Particularly strong need for TypeScript/React, Node.js, Go, and Kubernetes skills. Smaller team means consultants get broad exposure and direct product impact.',
  },
]
